In [1]:
import pandas as pd
import numpy as np

In [2]:
data = pd.read_json('artists/artists.json', orient = 'index').reset_index() 
data.head()

,index,name,decades,genres,styles,members,releases,num_songs,similar,influencer,followers,associated,birthdate,birthdate.id,birthplace,birthplace.id,deathdate,deathdate.id,deathplace,deathplace.id
0,mn0001935086,Short List,[2000],{'pop-rock-ma0000002613': 'Pop/Rock'},{},"[andy-stewart-hamilton-mn0002082143, gary-twig...",[2002-05-20-Ruff Burglar],12.0,[],[],[],[roger-chapman-mn0000296347],NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,mn0002572506,Doctor Wu',[],{'pop-rock-ma0000002613': 'Pop/Rock'},{},[],[],23.0,[],[],[],[],NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,mn0000812492,John Felice,[1980],{'pop-rock-ma0000002613': 'Pop/Rock'},"{'garage-rock-ma0000004458': 'Garage Rock', 'h...",[],[1988-??-??-Nothing Pretty],14.0,[mellow-drunk-mn0002312107],[],[],"[the-real-kids-mn0000490620, john-felice-the-l...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,mn0001517203,Kiko & Shara,[2000],{'latin-ma0000002692': 'Latin'},{'latin-pop-ma0000004461': 'Latin Pop'},"[kiko-mn0002080774, shara-mn0001960075]","[2006-05-23-Kiko & Shara, 2006-10-26-Kiko & Sh...",46.0,"[canelita-mn0001592347, haash-mn0000407099, yu...",[],[],"[los-ca%C3%B1os-mn0001842555, ismael-moya-mn00...",2005,2005,NaN,NaN,NaN,NaN,NaN,NaN
4,mn0001950898,Little Feather,[2010],{'country-ma0000002532': 'Country'},{'contemporary-country-ma0000002946': 'Contemp...,[],[2016-09-29-Little Feather],11.0,"[angaleena-presley-mn0002494476, dixie-chicks-...",[],[],[],NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [3]:
d = data.copy()
d.rename(columns = {'index': 'ID'}, inplace = True)
del (data)
d.head()

,ID,name,decades,genres,styles,members,releases,num_songs,similar,influencer,followers,associated,birthdate,birthdate.id,birthplace,birthplace.id,deathdate,deathdate.id,deathplace,deathplace.id
0,mn0001935086,Short List,[2000],{'pop-rock-ma0000002613': 'Pop/Rock'},{},"[andy-stewart-hamilton-mn0002082143, gary-twig...",[2002-05-20-Ruff Burglar],12.0,[],[],[],[roger-chapman-mn0000296347],NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,mn0002572506,Doctor Wu',[],{'pop-rock-ma0000002613': 'Pop/Rock'},{},[],[],23.0,[],[],[],[],NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,mn0000812492,John Felice,[1980],{'pop-rock-ma0000002613': 'Pop/Rock'},"{'garage-rock-ma0000004458': 'Garage Rock', 'h...",[],[1988-??-??-Nothing Pretty],14.0,[mellow-drunk-mn0002312107],[],[],"[the-real-kids-mn0000490620, john-felice-the-l...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,mn0001517203,Kiko & Shara,[2000],{'latin-ma0000002692': 'Latin'},{'latin-pop-ma0000004461': 'Latin Pop'},"[kiko-mn0002080774, shara-mn0001960075]","[2006-05-23-Kiko & Shara, 2006-10-26-Kiko & Sh...",46.0,"[canelita-mn0001592347, haash-mn0000407099, yu...",[],[],"[los-ca%C3%B1os-mn0001842555, ismael-moya-mn00...",2005,2005,NaN,NaN,NaN,NaN,NaN,NaN
4,mn0001950898,Little Feather,[2010],{'country-ma0000002532': 'Country'},{'contemporary-country-ma0000002946': 'Contemp...,[],[2016-09-29-Little Feather],11.0,"[angaleena-presley-mn0002494476, dixie-chicks-...",[],[],[],NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [4]:
d = d.dropna(axis = 0, subset = 'birthdate') 
d = d[d['decades'].map(lambda i: len(i)) > 0]
d['birthdate'] = d['birthdate'].str.replace('ca ', '')
d['birthdate'] = d['birthdate'].str.replace('ca. ', '')

d['birthdate'] = pd.to_datetime(d['birthdate'], yearfirst = True, errors = 'coerce')
d = d.dropna(axis = 0, subset = 'birthdate')

/var/folders/tn/p7vqjv8s24q1q6g_22mfss6m0000gn/T/ipykernel_68754/3475375781.py:4: FutureWarning: The default value of regex will change from True to False in a future version.
  d['birthdate'] = d['birthdate'].str.replace('ca. ', '')

In [5]:
d.head()

,ID,name,decades,genres,styles,members,releases,num_songs,similar,influencer,followers,associated,birthdate,birthdate.id,birthplace,birthplace.id,deathdate,deathdate.id,deathplace,deathplace.id
3,mn0001517203,Kiko & Shara,[2000],{'latin-ma0000002692': 'Latin'},{'latin-pop-ma0000004461': 'Latin Pop'},"[kiko-mn0002080774, shara-mn0001960075]","[2006-05-23-Kiko & Shara, 2006-10-26-Kiko & Sh...",46.0,"[canelita-mn0001592347, haash-mn0000407099, yu...",[],[],"[los-ca%C3%B1os-mn0001842555, ismael-moya-mn00...",2005-01-01,2005,NaN,NaN,NaN,NaN,NaN,NaN
5,mn0000249175,Les Baxter,"[1940, 1950, 1960, 1970]",{'easy-listening-ma0000002567': 'Easy Listenin...,"{'exotica-ma0000002581': 'Exotica', 'lounge-ma...",[],"[1948-??-??-Music Out of the Moon, 1952-??-??-...",987.0,"[esquivel-mn0000198923, living-strings-mn00002...","[artie-shaw-mn0000511029, benny-goodman-mn0000...","[combustible-edison-mn0000112815, dimitri-from...","[yma-sumac-mn0000685751, bas-sheva-mn000160796...",1922-03-14,1922-03-14,"Detroit, MI",detroit-mi-mz0000016067,"January 15, 1996",1996-01-15,"Palm Springs, CA",palm-springs-ca-mz0000017406
10,mn0000774879,Ky-Mani Marley,"[2000, 2010]",{'reggae-ma0000002820': 'Reggae'},{'contemporary-reggae-ma0000011892': 'Contempo...,[],"[2000-08-22-The Journey, 2001-05-29-Many More ...",114.0,"[ziggy-marley-mn0000697350, damian-marley-mn00...",[],[],"[ky-mani-mn0000089646, ky-mani-prince-be-mn000...",1976-02-26,1976-02-26,"Falmouth, Jamaica",falmouth-jamaica-mz0000039294,NaN,NaN,NaN,NaN
11,mn0003750097,Johnnie Mikel,[2010],{'pop-rock-ma0000002613': 'Pop/Rock'},"{'club-dance-ma0000002544': 'Club/Dance', 'dan...",[],[2018-03-??-Friday Night],NaN,"[superfruit-mn0003608258, trevor-moran-mn00033...","[aerosmith-mn0000604852, billy-joel-mn00000859...",[],[],1991-11-11,1991-11-11,Kentucky,kentucky-mz0000224444,NaN,NaN,NaN,NaN
18,mn0002744012,Rizzle Kicks,[2010],"{'rap-ma0000002816': 'Rap', 'pop-rock-ma000000...","{'british-rap-ma0000012265': 'British Rap', 'p...",[jimi-charles-moody-mn0003438099],"[2011-10-24-Stereo Typical, 2013-09-02-Roaring...",52.0,"[dappy-mn0002541254, example-mn0002139647, loi...","[de-la-soul-mn0000238322, dream-warriors-mn000...",[],[],2008-01-01,2008,"Brighton, Sussex, England",brighton-sussex-england-mz0000019256,NaN,NaN,NaN,NaN

In [6]:
dsort = d.sort_values(by='birthdate')
dsort.reset_index(drop=True, inplace=True)

In [7]:
dsort

,ID,name,decades,genres,styles,members,releases,num_songs,similar,influencer,followers,associated,birthdate,birthdate.id,birthplace,birthplace.id,deathdate,deathdate.id,deathplace,deathplace.id
0,mn0001448277,Carl Philipp Emanuel Bach,[2010],"{'classical-ma0000002521': 'Classical', 'child...","{'keyboard-ma0000011828': 'Keyboard', 'chamber...",[],[],NaN,"[johann-christian-bach-mn0002132738, wilhelm-f...",[johann-sebastian-bach-mn0000075140],[],[],1714-03-08,1714-03-08,"Weimar, Germany",weimar-germany-mz0000030577,"December 14, 1788",1788-12-14,"Hamburg, Germany",hamburg-germany-mz0000002352
1,mn0001504559,Mariinsky (Kirov) Theater Orchestra,[2010],"{'classical-ma0000002521': 'Classical', 'child...","{'ballet-ma0000004505': 'Ballet', 'opera-ma000...",[],"[1991-10-??-Prokofiev: Romeo and Juliet, 1992-...",67.0,"[bolshoi-theater-orchestra-mn0002341000, st-pe...",[],[],[],1729-01-01,1729,"St. Petersburg, Russia",st-petersburg-russia-mz0000008296,NaN,NaN,NaN,NaN
2,mn0001398790,P.D.Q. Bach,"[1960, 1970, 1980, 1990]","{'classical-ma0000002521': 'Classical', 'comed...","{'satire-ma0000011993': 'Satire', 'song-parody...",[],"[1965-??-??-An Evening with P.D.Q. Bach, 1966-...",52.0,[victor-borge-mn0000203804],"[darius-milhaud-mn0001175393, roy-harris-mn000...",[],[peter-schickele-mn0000678356],1742-04-01,1742-04-01,"Leipzig, Germany",leipzig-germany-mz0000004847,"May 5, 1807",1807-05-05,Wein-am-Rhein,wein-am-rhein-mz0000222443
3,mn0000236622,Bergen Philharmonic Orchestra,"[1990, 2000, 2010]",{'classical-ma0000002521': 'Classical'},"{'orchestral-ma0000004499': 'Orchestral', 'sym...",[],"[1985-??-??-Antonio Bibalo: Gespenster, 1986-?...",19.0,"[dresden-staatskapelle-mn0001647353, leipzig-g...",[],[],[],1765-01-01,1765,"Bergen, Norway",bergen-norway-mz0000008380,NaN,NaN,NaN,NaN
4,mn0001648323,La Scala Theater Chorus,"[1890, 1900, 1910, 1920, 1930, 1940, 1950, 196...",{'classical-ma0000002521': 'Classical'},{'opera-ma0000004512': 'Opera'},[],[],7.0,"[la-fenice-theater-chorus-mn0002275198, rome-o...",[],[],[],1778-01-01,1778,"Milan, Italy",milan-italy-mz0000006385,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
42780,mn0003734838,At Wendys,[2010],{'comedy-spoken-ma0000004433': 'Comedy/Spoken'...,"{'comedy-ma0000002525': 'Comedy', 'novelty-ma0...",[],[2018-03-23-We Beefin? EP],NaN,"[lil-windex-mn0003733265, big-shaq-mn000367397...",[],[],[],2018-01-01,2018,NaN,NaN,NaN,NaN,NaN,NaN
42781,mn0003777086,Winnetka Bowling League,[2010],{'pop-rock-ma0000002613': 'Pop/Rock'},{'adult-alternative-pop-rock-ma0000004488': 'A...,"[dan-book-mn0000561418, matthew-koma-mn0002786...",[],5.0,"[tall-heights-mn0003088277, lovelytheband-mn00...",[],[],[],2018-01-01,2018,"Los Angeles, CA",los-angeles-ca-mz0000002565,NaN,NaN,NaN,NaN
42782,mn0003813922,Ateez,[2010],"{'rap-ma0000002816': 'Rap', 'pop-rock-ma000000...","{'korean-pop-ma0000011907': 'Korean Pop', 'pop...",[],"[2019-01-15-Treasure EP 2: Zero To One, ]",6.0,"[bts-mn0003136056, ikon-mn0003444562, infinite...",[],[],[],2018-01-01,2018,NaN,NaN,NaN,NaN,NaN,NaN
42783,mn0003817423,Tomorrow X Together,[2010],{'pop-rock-ma0000002613': 'Pop/Rock'},"{'korean-pop-ma0000011907': 'Korean Pop', 'asi...",[],[2019-03-04-The Dream Chapter: Star],5.0,"[got7-mn0003217723, nct-mn0003116631, seventee...",[],[],[],2019-01-01,2019,NaN,NaN,NaN,NaN,NaN,NaN
42784,mn0003809851,Simple Creatures,[2010],{'pop-rock-ma0000002613': 'Pop/Rock'},"{'emo-pop-ma0000012243': 'Emo-Pop', 'alternati...",[],"[, ]",1.0,"[all-time-low-mn0000736318, the-summer-set-mn0...",[the-cure-mn0000137390],[],"[all-time-low-mn0000736318, blink-182-mn000075...",2019-01-01,2019,NaN,NaN,NaN,NaN,NaN,NaN

In [8]:
beatles = dsort[dsort['name']=='The Beatles']
beatles

,ID,name,decades,genres,styles,members,releases,num_songs,similar,influencer,followers,associated,birthdate,birthdate.id,birthplace,birthplace.id,deathdate,deathdate.id,deathplace,deathplace.id
13752,mn0000754032,The Beatles,[1960],{'pop-rock-ma0000002613': 'Pop/Rock'},{'british-invasion-ma0000002484': 'British Inv...,"[george-harrison-mn0000209142, john-lennon-mn0...","[1963-03-22-Please Please Me, 1963-11-22-With ...",2062.0,"[the-beach-boys-mn0000041874, the-kinks-mn0000...","[buddy-holly-mn0000538677, carl-perkins-mn0000...","[10cc-mn0000502163, badfinger-mn0000064303, be...","[george-harrison-mn0000209142, george-martin-m...",1957-01-01,1957,"Liverpool, Lancashire, England",liverpool-lancashire-england-mz0000008965,1970,1970,NaN,NaN

In [9]:
beatles['influencer'].values

array([list(['buddy-holly-mn0000538677', 'carl-perkins-mn0000792953', 'chuck-berry-mn0000120521', 'elvis-presley-mn0000180228', 'fats-domino-mn0000137494', 'gene-vincent-mn0000803720', 'little-richard-mn0000824022', 'lonnie-donegan-mn0000277549', 'phil-spector-mn0000694967', 'ravi-shankar-mn0000404463', 'roy-orbison-mn0000852007', 'the-everly-brothers-mn0000046699', 'the-isley-brothers-mn0000766893', 'arthur-alexander-mn0000931202', 'eddie-cochran-mn0000793988', 'larry-williams-mn0000135024', 'smokey-robinson-mn0000821571', 'bob-dylan-mn0000066915', 'the-shirelles-mn0000418981', 'the-supremes-mn0000477875', 'little-willie-john-mn0000269972', 'the-marvelettes-mn0000376608', 'the-shadows-mn0000496405', 'bill-haley-mn0000077870', 'buck-owens-mn0000941579', 'jerry-lee-lewis-mn0000332141', 'johnny-kidd-the-pirates-mn0000239961'])],
      dtype=object)

In [10]:
beatles['followers'].values

array([list(['10cc-mn0000502163', 'badfinger-mn0000064303', 'bee-gees-mn0000043714', 'cheap-trick-mn0000105354', 'david-bowie-mn0000531986', 'donovan-mn0000799053', 'electric-light-orchestra-mn0000163229', 'harry-nilsson-mn0000560208', 'oasis-mn0000393345', 'supertramp-mn0000033666', 'the-byrds-mn0000631774', 'the-monkees-mn0000478603', 'the-moody-blues-mn0000404434', 'the-rutles-mn0000897214', 'the-zombies-mn0000582313', 'todd-rundgren-mn0000936425', 'aerosmith-mn0000604852', 'big-star-mn0000051992', 'billy-joel-mn0000085915', 'boston-mn0000079960', 'carpenters-mn0000051909', 'cat-stevens-mn0000198480', 'cream-mn0000112462', 'crowded-house-mn0000130173', 'dwight-twilley-mn0000161572', 'elton-john-mn0000796734', 'emitt-rhodes-mn0000800926', 'flamin-groovies-mn0000180263', 'foo-fighters-mn0000184043', 'genesis-mn0000199995', 'jeff-lynne-mn0000228266', 'jefferson-airplane-mn0000840102', 'jellyfish-mn0000319021', 'jimi-hendrix-mn0000354105', 'jonathan-richman-mn0000266255', 'love-mn0000314600', 'matthew-sweet-mn0000387530', 'moby-grape-mn0000569914', 'peter-gordon-mn0000264860', 'peter-frampton-mn0000320845', 'pink-floyd-mn0000346336', 'pixies-mn0000895136', 'rick-springfield-mn0000359613', 'robyn-hitchcock-mn0000832524', 'simon-garfunkel-mn0000038936', 'sonny-cher-mn0000042993', 'squeeze-mn0000790732', 'syd-barrett-mn0000044874', 't-rex-mn0000005882', 'the-association-mn0000753963', 'the-beau-brummels-mn0000135032', 'the-cars-mn0000061172', 'the-dbs-mn0000489209', 'the-dukes-of-stratosphear-mn0000142963', 'the-jam-mn0000084053', 'the-knack-mn0000087179', 'the-las-mn0000104455', 'the-left-banke-mn0000771010', 'the-london-souls-mn0000993916', 'the-lovin-spoonful-mn0000052900', 'the-mamas-the-papas-mn0000059293', 'the-move-mn0000483587', 'the-raspberries-mn0000416245', 'the-residents-mn0000420539', 'the-spongetones-mn0000485869', 'the-stone-roses-mn0000564333', 'the-turtles-mn0000564239', 'the-who-mn0000577627', 'tom-petty-mn0000612716', 'xtc-mn0000678339', 'yes-mn0000685647', 'abba-mn0000922728', 'abc-mn0000574597', 'ambrosia-mn0000019133', 'argent-mn0000593930', 'aztec-camera-mn0000759031', 'bay-city-rollers-mn0000151979', 'billy-squier-mn0000084814', 'blue-%C3yster-cult-mn0000061938', 'blur-mn0000758444', 'bread-mn0000610706', 'buffalo-springfield-mn0000939567', 'chad-jeremy-mn0000799644', 'coldplay-mn0000775877', 'elliott-smith-mn0000172167', 'emerson-lake-palmer-mn0000798992', 'fleetwood-mac-mn0000182900', 'hermans-hermits-mn0000575051', 'h%C3%BCsker-d%C3%BC-mn0000639053', 'iron-butterfly-mn0000772567', 'james-taylor-mn0000204386', 'jason-falkner-mn0000217893', 'joe-jackson-mn0000784732', 'led-zeppelin-mn0000139026', 'lloyd-cole-mn0000229348', 'manfred-mann-mn0002285572', 'marshall-crenshaw-mn0000853492', 'neutral-milk-hotel-mn0000863102', 'nick-lowe-mn0000866841', 'prefab-sprout-mn0000300024', 'procol-harum-mn0000304401', 'queen-mn0000858827', 'r-stevie-moore-mn0000384920', 'rockpile-mn0000243012', 'steely-dan-mn0000011707', 'supergrass-mn0000031556', 'teenage-fanclub-mn0000015694', 'the-alan-parsons-project-mn0001176481', 'the-apples-in-stereo-mn0000026023', 'the-chameleons-uk-mn0001557918', 'the-church-mn0000764181', 'the-dream-academy-mn0000803513', 'the-feelies-mn0000762177', 'the-go-gos-mn0000766385', 'the-guess-who-mn0000061480', 'the-house-of-love-mn0000080720', 'the-idle-race-mn0000081981', 'the-iveys-mn0000082755', 'the-merry-go-round-mn0000474208', 'the-nazz-mn0000377892', 'the-neon-philharmonic-mn0000400322', 'the-nice-mn0000481061', 'the-police-mn0000413524', 'the-posies-mn0000490554', 'the-replacements-mn0000422405', 'the-smithereens-mn0000898479', 'the-soft-boys-mn0000501802', 'the-three-oclock-mn0000571806', 'traffic-mn0000012472', 'travis-mn0000013508', 'u2-mn0000219203', 'utopia-mn0000837486', 'world-party-mn0000958768', 'ari-roar-mn0003732622', 'belle-and-sebastian-mn0000153565', 'freddie-the-dreamers-mn0000177558', 'george-michael-mn0000545074', 'grateful-dead-mn0000988440', 'its-a-beautiful-day-mn0000109012', 'jackson-browne-mn0000130689', 'kansas-mn0000303626', 'kate-bush-mn0000855423', 'king-crimson-mn0000076057', 'lenny-kravitz-mn0000200074', 'm-ward-mn0000217641', 'marmalade-mn0000334054', 'michael-jackson-mn0000467203', 'mott-the-hoople-mn0000596126', 'nirvana-mn0000357406', 'prince-mn0000361393', 'quicksilver-messenger-service-mn0000317417', 'sebadoh-mn0000840523', 'sloan-mn0000029978', 'small-faces-mn0000423267', 'spirit-mn0000746010', 'split-enz-mn0000747757', 'spoon-mn0000131038', 'status-quo-mn0000745241', 'the-rockin-berries-mn0000486115', 'the-rubinoos-mn0000297955', 'the-sir-douglas-quintet-mn0000018708', 'third-eye-blind-mn0000926237', 'vanilla-fudge-mn0000311674', 'weezer-mn0000243008', 'aj-mitchell-mn0003779965', 'apoptygma-berzerk-mn0000496556', 'big-time-rush-mn0002534053', 'blossoms-mn0003457444', 'claypool-lennon-delirium-mn0003475083', 'color-bars-mn0000322277', 'danger-mouse-mn0000674440', 'devan-dubois-mn0003295166', 'empty-hearts-mn0002919875', 'fauna-flora-mn0003251033', 'fictionist-mn0001049792', 'finish-ticket-mn0002883447', 'forever-in-your-mind-mn0003408500', 'fruition-mn0003181047', 'glee-mn0001790434', 'hailey-knox-mn0003514849', 'harry-styles-mn0002854537', 'james-supercave-mn0003386362', 'jigsaw-mn0001032454', 'john-mccullagh-mn0003154359', 'johnnie-mikel-mn0003750097', 'klangstof-mn0003509025', 'kyle-craft-mn0001476358', 'la-salami-mn0003514363', 'levitation-room-mn0003462983', 'lukas-graham-mn0003065843', 'mainland-mn0001470961', 'matt-simons-mn0001019633', 'mayday-mn0000866769', 'mikey-wax-mn0001737958', 'mo-troper-mn0003289108', 'nick-howard-mn0003046755', 'nick-piunti-mn0001522059', 'pete-macleod-mn0001495727', 'phil-ajjarapu-mn0001325237', 'portugal-the-man-mn0000716469', 'san-mei-mn0003679560', 'shawn-hook-mn0002926957', 'sivert-h%C3%B8yem-mn0001314128', 'sweet-baboo-mn0002149390', 'telly-leung-mn0002064826', 'the-creases-mn0003176107', 'the-kik-mn0001577499', 'the-legal-matters-mn0003263088', 'the-lemon-twigs-mn0003539906', 'the-maine-mn0000667657', 'the-pretty-reckless-mn0001630569', 'the-shilohs-mn0002892516', 'trent-dabbs-mn0000810208', 'trevor-james-tillery-mn0003501658', 'viola-beach-mn0003472410', 'violet-days-mn0003457364', 'yungblud-mn0003637248', 'zuzu-mn0001508600'])],
      dtype=object)

In [11]:
adjacency = np.zeros(shape = (len(dsort), len(dsort)))
# adjacency = np.zeros(shape = (1000,1000))

for i in range(len(dsort) - 1): 
    for influencer in dsort.loc[i, 'influencer']:
        id = "mn" + influencer.split('-mn')[1]
        
        if len(dsort[dsort['ID'] == id].index) == 1:
            id = dsort[dsort['ID'] == id].index[0]
            adjacency[i, id] = 1
    for follower in dsort.loc[i, 'followers']:
            id = "mn" + follower.split('-mn')[1]
            
            if len(dsort[dsort['ID'] == id].index) == 1:
                id = dsort[dsort['ID'] == id].index[0]
                adjacency[id, i] = 1